<!--
<div class="jumbotron">
    <h1>Login to <span class="zf-green">Admin Panel</span></h1>
    <form action="" method="post">
		User Name: <input type="text" name="user_name" value="" /><br />
		Password: <input type="password" name="password" value="" /><br />
		<input type="submit" name="submit" value="Submit" />
	</form>
</div>
-->
Hello Admin!!

 <div><a href="<?php echo $this->url('zfcuser/logout') ?>"><?php echo $this->translate('Sign Out'); ?></a></div>
 
 <div class="classified">
  <div><a href="<?php echo $this->url('classified') ?>"><?php echo $this->translate('Classified'); ?></a></div>
 </div>